// swift-tools-version: 5.7
// ⚠️ 此文件由 CI 自动生成，请勿手动修改。
// ⚠️ This file is auto-generated by CI. Do not edit manually.
import PackageDescription

let package = Package(
    name: "OCRKit",
    platforms: [.iOS(.v15)],
    products: [
        .library(name: "OCRKit", targets: ["OCRKit"]),
    ],
    targets: [
        .binaryTarget(
            name: "OCRKit",
            url: "https://github.com/FreakLee/OCRKit-Release/releases/download/v1.0.0/OCRKit.xcframework.zip",
            checksum: "CHECKSUM_PLACEHOLDER"
        ),
    ]
)
